# Python NumPy Array

NumPy is the shorter version for Numerical Python. Numpy is the foundation to introduce Data Science into Python. The Python NumPy package has built-in functions that are required to perform Data Analysis and Scientific Computing.

All the other packages that we use for data analysis built on top of this Numpy module. That’s why one has to master this Python Numpy module before start working with DataFrames or Data analysis.

# Creating Python ndarray

The Python Numpy module has a ndarray object, shorter version of N-dimensional array, or an array. Like any other programming language array, this Numpy ndarray object allows you to store multiple items of the same data type.

# EXAMPLE - 1: Create an Array in Python using the array function

In [2]:
import numpy as np
 
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
 
print(arr)

[1 2 3 4 5 6 7 8 9]


# EXAMPLE - 2: Create an Array from List in Python

In [4]:
import numpy as np

a = [1, 2, 3, 4, 5]
arr = np.array(a)
 
print(arr)

[1 2 3 4 5]


# EXAMPLE - 3 :Create an ndarray of mixed items in Python.

In [5]:
import numpy as np
a = [2.5, 3.5, 7, 4.5, 8]
arr = np.array(a)
print(arr)

[2.5 3.5 7.  4.5 8. ]


# TO KNOW THE DT OF ELEMENTS STORED IN AN ARRAY - NUMPY

In [1]:
import numpy as np
a = np.array([(1,2,3)])
print(a.dtype)

int32


# You can find the size and shape of the array using ‘size’ and ‘shape’ function respectively.

In [5]:
import numpy as np
a = np.array([(1,2,3,4,5,6)])
print(a.size)
print(a.shape)

6
(1, 6)


# Create a Python Numpy ndarray from a list of lists. 
Here, we declared a nested list of lists with integer values. Next, we used the array function to convert the list to Numpy array.

In [7]:
import numpy as np
a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print('List of List = ', a)
print()
 
arr = np.array(a)
print(arr)
print(arr.size)
print(arr.shape)

List of List =  [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
(3, 3)


# RESHAPING AN ARRAY

In [10]:
import numpy as np
a = np.array([(8,9,10),(11,12,13)])
print('BEFORE')
print(a)
print(a.size)
print(a.shape)
print('AFTER')
a=a.reshape(3,2)
print(a)
print(a.size)
print(a.shape)

BEFORE
[[ 8  9 10]
 [11 12 13]]
6
(2, 3)
AFTER
[[ 8  9]
 [10 11]
 [12 13]]
6
(3, 2)


In [ ]:
# ARITHMETIC OPERATIONS IN ARRAY

In [7]:
import numpy as np
a = [1, 2, 3, 4, 5]
arr = np.array(a)
  
print('Original Array      = ', arr)
print('Add 5 to Array      = ', arr + 5)
print('Multiply arr with 2 = ', arr * 2)

Original Array      =  [1 2 3 4 5]
Add 5 to Array      =  [ 6  7  8  9 10]
Multiply arr with 2 =  [ 2  4  6  8 10]


# Create an Array from Tuple

In [8]:
import numpy as np

tup = (10, 20, 30)
arr = np.array(tup)

print(arr)

[10 20 30]


# Python NumPy Two Dimensional Array
Placing or Nesting two lists inside a [] brackets create a two-dimensional array.

In [9]:
import numpy as np
 
two_arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
 
print(two_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


# Python NumPy Three Dimensional Array

In [ ]:
Here, we are creating a 3 * 3 matrix or three-dimensional array.

In [10]:
import numpy as np
 
three_arr = np.array([[1, 2, 3], [10, 20, 30], [6, 7, 8]])
 
print(three_arr)

[[ 1  2  3]
 [10 20 30]
 [ 6  7  8]]


# Create an Array using srange

In this example, we are using the Python Numpy arange function to create an array of numbers range from 0 to n-1, where n is the given number. For example, np.arange(5) retunes an array of numbers in sequence from 0 to 4.

In [13]:
import numpy as np

np.arange(5)

array([0, 1, 2, 3, 4])

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Create an Array using linspace in Python

In this example, we used the Python Numpy linspace function. The syntax behind this function is:

In [ ]:
np.linspace(start, end_value, steps)

Here, we created three arrays of numbers range from 0 to n serrated by steps. For example, np.linspace(0, 1, 5) retunes an array of numbers from 0 to 1 in five equal steps.

In [16]:
import numpy as np

np.linspace(0, 1, 5)
np.linspace(0, 10, 5)

np.linspace(0, 1, 7)
np.linspace(10, 100, 20)

array([ 10.        ,  14.73684211,  19.47368421,  24.21052632,
        28.94736842,  33.68421053,  38.42105263,  43.15789474,
        47.89473684,  52.63157895,  57.36842105,  62.10526316,
        66.84210526,  71.57894737,  76.31578947,  81.05263158,
        85.78947368,  90.52631579,  95.26315789, 100.        ])

# Python zeros array

The Python zeros function creates an array of zeros. This function accepts the arguments to specify the shape of an array. For example,

zeros(2) means a one-dimensional array of two zero elements.
zeros(2, 3) means 2 * 3 matrix of zeros.
and zeros(2, 3, 4) means a three-dimensional array of zeros.

In [17]:
import numpy as np
np.zeros(3)
np.zeros((2, 2))

np.zeros((2, 3))
np.zeros((4, 7))
np.zeros((3, 2, 7))

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])

# Python ones array

In [18]:
import numpy as np

np.ones(5)
np.ones((3, 3))
np.ones((3, 5))
np.ones((3, 2, 9))

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

# Python full array
The NumPy full function creates an array of a given number.

In [19]:
import numpy as np

# Returns one dimensional array of 4’s of size 5
np.full((5), 4)

# Returns 3 * matrix of number 9
np.full((3, 4), 9)
np.full((4, 4), 8)
np.full((2, 3, 6), 7)

array([[[7, 7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7, 7]],

       [[7, 7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7, 7]]])

# Python identical array
The Python eye function creates an identical N * N matrix, where N is the given argument value.

In [20]:
import numpy as np
np.eye(2)
np.eye(3)
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Python diagonal array
The Python diag function creates an identical, where diagonal values filled with the list values.

In [21]:
import numpy as np
np.diag([3])
np.diag([1, 2])
np.diag([1, 2, 3, 4])
np.diag([1, 2, 3, 4, 5, 6])

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

# Accessing Numpy Array Items

Like any other programming language, you can access the array items using the index position. The index position always starts at 0 and ends at n-1, where n is the array size, row size, or column size, or dimension.

In [25]:
import numpy as np
arr = np.array([10, 15, 25, 35, 45, 55, 65])
arr

arr[0]
arr[2]
arr[5]
#arr[7]
arr[2:5]

array([25, 35, 45])

In [26]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5],[12, 15, 61, 11, 19]])
arr[0][1]
arr[0][4]
arr[1][1]
arr[1][4]

19

# Python NumPy Arithmetic Operations

Python Numpy module provides various arithmetic functions such as add, subtract, multiply and divide, which performs Python numpy arithmetic operations on arrays. Apart from them, you can use the standard Python Arithmetic Operators also. Arrays should be of the same shape, or they have to bound to array rules to use Numpy arithmetic functions.

In [28]:
a = np.array([10, 50, 100, 150, 250])
a 

array([ 10,  50, 100, 150, 250])

In [29]:
b = np.array([6, 5, 4, 3, 2])
b


array([6, 5, 4, 3, 2])

In [30]:
 
c = np.array([[26,  48,  91,  57, 120], [33,  95,  68, 109, 155], [111, 194,   7,  22, 124], [ 82, 119,  18, 156,  81],[ 38,  10, 151,  24,  14]])
c


array([[ 26,  48,  91,  57, 120],
       [ 33,  95,  68, 109, 155],
       [111, 194,   7,  22, 124],
       [ 82, 119,  18, 156,  81],
       [ 38,  10, 151,  24,  14]])

In [32]:
#You can create an array of random numbers using the below statement
c = np.random.randint(0, 200, size = (5, 5))
c


array([[ 67,  25,  55,  54,  73],
       [ 25,  35, 113,  26, 123],
       [156,  24,  22,  34,  26],
       [ 80, 168, 129,  40, 197],
       [113,  84,  15, 131, 131]])

In [33]:
 d = np.array([[12, 11,  0,  9,  7], [10,  4, 11,  6,  9], [ 9,  2, 10,  9, 11], [ 5, 14,  0, 11,  8], [ 5, 12,  5,  5, 11]])
d


array([[12, 11,  0,  9,  7],
       [10,  4, 11,  6,  9],
       [ 9,  2, 10,  9, 11],
       [ 5, 14,  0, 11,  8],
       [ 5, 12,  5,  5, 11]])

In [34]:
d = np.random.randint(0, 15, size = (5, 5))
d


array([[ 9, 13, 14,  3,  1],
       [ 8, 12, 10,  2,  6],
       [ 3, 13, 14,  2,  3],
       [ 7,  9, 13,  0,  5],
       [ 0,  7, 12,  3,  5]])

In [35]:
e = np.array([11, 22, 33, 44, 55])
e

array([11, 22, 33, 44, 55])

# Python NumPy Arithmetic Operations Examples
The following are the list of arithmetic operators and arithmetic functions that are available to perform NumPy Arithmetic Operations in Python

# Python NumPy add function
This NumPy add function adds two arrays.

In [36]:
np.add(a, b)

array([ 16,  55, 104, 153, 252])

In [37]:
np.add(c, d)

array([[ 76,  38,  69,  57,  74],
       [ 33,  47, 123,  28, 129],
       [159,  37,  36,  36,  29],
       [ 87, 177, 142,  40, 202],
       [113,  91,  27, 134, 136]])

In [ ]:
Let me try to add an array of different sizes

In [38]:
np.add(a, c)

array([[ 77,  75, 155, 204, 323],
       [ 35,  85, 213, 176, 373],
       [166,  74, 122, 184, 276],
       [ 90, 218, 229, 190, 447],
       [123, 134, 115, 281, 381]])

In [39]:
np.add(a, b, c)

array([[ 16,  55, 104, 153, 252],
       [ 16,  55, 104, 153, 252],
       [ 16,  55, 104, 153, 252],
       [ 16,  55, 104, 153, 252],
       [ 16,  55, 104, 153, 252]])

# Python NumPy multiply function

In [ ]:
np.multiply(a, b)
np.multiply(c, d)
np.multiply(d, c)

# Python random Array
In Python, we have the random module used to generate random numbers of a given type using the PRNG algorithm. Here, we are going to discuss the list of available functions to generate a random array in Python.

# Python random Array using rand

The Numpy random rand function creates an array of random numbers from 0 to 1. Here, you have to specify the shape of an array.

In [40]:
import numpy as np
 
arr = np.random.rand(7)
 
print('-----Generated Random Array----')
print(arr)
 
arr2 = np.random.rand(10)
print('\n-----Generated Random Array----')
print(arr2)

-----Generated Random Array----
[0.66026448 0.20136701 0.84043657 0.69123284 0.53069021 0.04896768
 0.62176452]

-----Generated Random Array----
[0.35469109 0.39900061 0.49598791 0.63376974 0.29699132 0.1217922
 0.48255268 0.56060244 0.90143731 0.07948159]


# Python 2D Random Array

In [41]:
import numpy as np
 
arr = np.random.rand(2, 2)
 
print('-----Generated Two Dimensional Random Array----')
print(arr)
 
arr2 = np.random.rand(4, 5)
print('\n-----Generated Two Dimensional Random Array----')
print(arr2)

-----Generated Two Dimensional Random Array----
[[0.77855182 0.57587048]
 [0.6483124  0.39397576]]

-----Generated Two Dimensional Random Array----
[[0.7507301  0.6887818  0.93008782 0.42538663 0.58887321]
 [0.22398949 0.75080657 0.42155883 0.66874496 0.73973141]
 [0.75773927 0.2044906  0.90309269 0.46730683 0.77519001]
 [0.64596413 0.65451267 0.00849265 0.12811517 0.74743693]]


# Python 3D Random Array

In [42]:
import numpy as np
 
arr = np.random.rand(2, 2, 2)
 
print('-----Generated Three Dimensional Random Array----')
print(arr)
 
arr2 = np.random.rand(2, 4, 5)
print('\n-----Generated Three Dimensional Random Array----')
print(arr2)

-----Generated Three Dimensional Random Array----
[[[0.51062732 0.90648752]
  [0.41555593 0.30730337]]

 [[0.82710775 0.49969206]
  [0.91140395 0.01796797]]]

-----Generated Three Dimensional Random Array----
[[[0.71729433 0.48797503 0.46463169 0.486938   0.74687242]
  [0.21030911 0.38557735 0.52813541 0.19946975 0.71495756]
  [0.09762073 0.5683974  0.33209718 0.7052584  0.84567171]
  [0.89653268 0.74935748 0.71811038 0.01580126 0.79928911]]

 [[0.36115036 0.27031126 0.13249328 0.53558138 0.34323228]
  [0.98143132 0.24205988 0.04301576 0.31614883 0.77894253]
  [0.13379004 0.24891087 0.06246573 0.91998593 0.60042199]
  [0.04909371 0.91643098 0.14422594 0.26207561 0.15851736]]]
