In [1]:
# numpy array
import numpy as np
arr = [1,2,3,4,5,6,7,8]
print(np.array(arr))

[1 2 3 4 5 6 7 8]


In [5]:
arr = [[1,2,3,4],[5,6,7,8]]
print(np.array(arr))
print(np.array(arr).shape) # 2*4 matrix 2 rows 4 columns

arr = np.array([(1,2),(2,5),(6,7)])
print(arr)
print(arr.shape) # 3*2 matrix 3 rows 2 columns

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1 2]
 [2 5]
 [6 7]]
(3, 2)


In [6]:
print(arr.dtype) # prvides the type of values present in the array

int32


In [8]:
arr = np.array([('apple','bannana'),('mango','orange')])
print(arr)
print(arr.dtype) # prvides the type of values present in the array

[['apple' 'bannana']
 ['mango' 'orange']]
<U7


In [9]:
arr = np.array([('apple','bannana'),('mango','orange')])
print(arr)
print(arr.size)

[['apple' 'bannana']
 ['mango' 'orange']]
4


In [12]:
# reshaping the matrix like 2*3 to 3*2 matrix
arr = np.array([(1,2,3,4),(5,6,7,8)])
print("before")
print(arr)
print("shape of matrix = ",arr.shape)
# rechsping the array
a = arr.reshape(4,2)
print("after reshaping")
print(a)
print("shape of matrix = ",a.shape)


before
[[1 2 3 4]
 [5 6 7 8]]
shape of matrix =  (2, 4)
after reshaping
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
shape of matrix =  (4, 2)


In [15]:
#creating a arraya from a tuple
tpl = (1,2,3,4)
arr = np.array(tpl)
print(arr)

# 3 dimensional array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

# createing the array using range of the number starting from 0 to n-1
arr = np.arange(17)
print(arr)

[1 2 3 4]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [19]:
# linespace which provides the range of from the start to end of how many numbers should be present
# linespace(start,end, steps to be taken to get to end)
print(np.linspace(4,15,5))
print(np.linspace(5,20,4))

[ 4.    6.75  9.5  12.25 15.  ]
[ 5. 10. 15. 20.]


In [25]:
# zeros which can used to provide the zeros in the matrix
print(np.zeros(3))
print(np.zeros((3,5))) #np.zeros((3,5))where in this zero only takes one argument (3,5) should be written 3rows and 5 colums
print(np.zeros((2,5,7))) # 2 rows, 5 rows in row of the first value, 7 colums

[0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]]


In [26]:
# ones which can used to provide the ones in the matrix
print(np.ones(3))
print(np.ones((3,5))) #np.zeros((3,5))where in this ones only takes one argument (3,5) should be written 3rows and 5 colums
print(np.ones((2,5,7))) # 2 rows, 5 rows in row of the first value, 7 colums

[1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[[1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]]


In [32]:
#Full which is used to take given number as matrix
# in full it takes 2 arguments 1 st is no of column
print(np.full((5),6)) # which is 5 row and  default if column not present row takes the part of column
print(np.full((5),6).shape)
print(np.full((5),6).size)
print("------------------------------")
print(np.full((5,3),6)) # which is 5 columns and 3 row
print(np.full((5,3),6).shape)
print(np.full((5,3),6).size)
print("------------------------------")
print(np.full((2,3,2),6)) # which is 5 columns and 3 row
print(np.full((2,3,2),6).shape)
print(np.full((2,3,2),6).size)


[6 6 6 6 6]
(5,)
5
------------------------------
[[6 6 6]
 [6 6 6]
 [6 6 6]
 [6 6 6]
 [6 6 6]]
(5, 3)
15
------------------------------
[[[6 6]
  [6 6]
  [6 6]]

 [[6 6]
  [6 6]
  [6 6]]]
(2, 3, 2)
12


In [37]:
# eye in numpy which give identicle element 1 in matrix in diagonal
print(np.eye(4))
print(np.eye(2))
print(np.eye(3))


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [42]:
# diag which gis the set of number in the diagonal
print(np.diag([3]))
print(np.diag([3,5]))
print(np.diag([1,2,3,4,5]))
np.diag([1,2,3,4,5])

[[3]]
[[3 0]
 [0 5]]
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [45]:
# accessing tthe array items
import numpy as np
arr = np.array([10, 15, 25, 35, 45, 55, 65])
print(arr)
print(arr[0])
print(arr[5])
print(arr[2:5])

[10 15 25 35 45 55 65]
10
55
[25 35 45]


In [46]:
#You can create an array of random numbers using the below statement
c = np.random.randint(0, 200, size = (5, 5))
c # creating random matrix of 0 to 200 of the size 5 * 5 matrix

array([[ 61, 145,  11, 115, 163],
       [ 68,  39, 110, 166,  56],
       [171,  31, 139, 166, 158],
       [ 78,  10, 154, 176,  48],
       [107, 105,  18,  93, 120]])

In [47]:
a = np.array([10, 50, 100, 150, 250])
b = np.array([6, 5, 4, 3, 2])
d = np.random.randint(0, 15, size = (5, 5))
e = np.array([11, 22, 33, 44, 55])

In [48]:
print(np.add(a, b))

[ 16  55 104 153 252]


In [49]:
print(np.add(c, d))

[[ 73 158  21 116 165]
 [ 78  43 118 170  61]
 [172  31 149 170 163]
 [ 90  10 155 188  61]
 [112 110  24 102 129]]


In [50]:
print(np.multiply(a, b))
print(np.multiply(c, d))
print(np.multiply(d, c))

[ 60 250 400 450 500]
[[ 732 1885  110  115  326]
 [ 680  156  880  664  280]
 [ 171    0 1390  664  790]
 [ 936    0  154 2112  624]
 [ 535  525  108  837 1080]]
[[ 732 1885  110  115  326]
 [ 680  156  880  664  280]
 [ 171    0 1390  664  790]
 [ 936    0  154 2112  624]
 [ 535  525  108  837 1080]]


In [51]:
import numpy as np
 
arr = np.random.rand(7)
 
print('-----Generated Random Array----')
print(arr)
 
arr2 = np.random.rand(10)
print('\n-----Generated Random Array----')
print(arr2)

-----Generated Random Array----
[0.01627136 0.20102299 0.60936356 0.38623176 0.24382185 0.93883362
 0.44748105]

-----Generated Random Array----
[0.77174371 0.80869672 0.24470732 0.02349038 0.28443483 0.00842
 0.77044554 0.86480116 0.00628603 0.30951333]
